name: joakimfong
favicon: null
layout_spectrum: 0.9883752311579883
typography_spectrum: 0.5739400174934417
title: Joakim Fong
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aca29e'
    - '#15130f'
    - '#905f45'
    - '#4075a8'
  brandStrength: 0.3125
  lightness: 0.5261356683913618
  saturation: 0.0352463242597878
  rhythmicContrast: 0.9509798858780414
purpose: []
